event_planning/lib/event_planning_web/router.ex
defmodule EventPlanningWeb.Router do
  use EventPlanningWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {EventPlanningWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", EventPlanningWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/login", LoginController, :index)

    post("/login", LoginController, :new)
    get("/success", LoginController, :success)

    get("/events/my_schedule", EventController, :my_schedule)
    get("/events/next_event", EventController, :next_event)
    resources("/users", UserController)
    resources("/events", EventController)
  end

  # resources "/u", UserController, only: [:index] do
  #   resources("/events", PostController)
  # end

  # Other scopes may use custom stacks.
  # scope "/api", EventPlanningWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: EventPlanningWeb.Telemetry)
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end
end

event_planning/lib/event_planning_web/templates/login/index.html.heex
<section class="row">
  <div class="column">
    <h1>
      Login
    </h1>
    <p>Use secret "password"</p>
  </div>
</section>

<section class="row">
  <div class="column"></div>
  <div class="column">
    <%= form_for :password, Routes.login_path(EventPlanningWeb.Endpoint, :new), fn f -> %>
      Password: <%= password_input(f, :password, value: "") %>
      <%= submit("Submit") %>
    <% end %>
  </div>
  <div class="column"></div>
</section>